apiVersion: v2
description: A Helm chart for the Simple-Backend-Nest-Service
name: simple-backend-nest-service
type: application
version: "0.5.9"
dependencies:
  - name: stateless-http-service
    version: "3.2.0"
  - name: helpers-library
    version: "0.0.1"
